//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace EntityFrameworkTest2.Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class dbee5034285b5e4e7885929fa50063900dEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new dbee5034285b5e4e7885929fa50063900dEntities object using the connection string found in the 'dbee5034285b5e4e7885929fa50063900dEntities' section of the application configuration file.
        /// </summary>
        public dbee5034285b5e4e7885929fa50063900dEntities() : base("name=dbee5034285b5e4e7885929fa50063900dEntities", "dbee5034285b5e4e7885929fa50063900dEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new dbee5034285b5e4e7885929fa50063900dEntities object.
        /// </summary>
        public dbee5034285b5e4e7885929fa50063900dEntities(string connectionString) : base(connectionString, "dbee5034285b5e4e7885929fa50063900dEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new dbee5034285b5e4e7885929fa50063900dEntities object.
        /// </summary>
        public dbee5034285b5e4e7885929fa50063900dEntities(EntityConnection connection) : base(connection, "dbee5034285b5e4e7885929fa50063900dEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Foo> Foos
        {
            get
            {
                if ((_Foos == null))
                {
                    _Foos = base.CreateObjectSet<Foo>("Foos");
                }
                return _Foos;
            }
        }
        private ObjectSet<Foo> _Foos;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Foos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFoos(Foo foo)
        {
            base.AddObject("Foos", foo);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbee5034285b5e4e7885929fa50063900dModel", Name="Foo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Foo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Foo object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Foo CreateFoo(global::System.Int32 id)
        {
            Foo foo = new Foo();
            foo.Id = id;
            return foo;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
    }

    #endregion
    
}
